### ISSUE TITLE
How to display collapsed by default?

### ISSUE THREAD

**Issue by sinanerdem** [cars10/vue-print-object#1]
Is there a possibility to display the objects collapsed by default?

**Comment by cars10** [comment]
Hi, great idea. I just published version `0.1.1` where you can do exactly that.

You can set a new prop named `initial-collapsed` when using the component. Set the prop to `true` to collapse all keys by default, set an array (for example `['key1', 'key2']` to only collapse specific keys.

**Comment by sinanerdem** [comment]
Thank you!

I just tried the latest version. It works. One minor issue: when the objects have no name, it is impossible to open them. Look at the second object on the attached screenshot. There is no clickable area on that second array.

<img width="928" alt="screen shot 2018-07-20 at 15 01 25" src="https://user-images.githubusercontent.com/608971/43001474-05ef364e-8c2e-11e8-8d97-14afd9aa06ad.png">

**Comment by cars10** [comment]
Yes, this is a known issue. I opened #2 for that and will later look into it.

**Comment by cars10** [comment]
Just wanted to let you know that i fixed this issue in 0.1.3.

**Comment by sinanerdem** [comment]
Tried 0.1.3 and everything seems to work ok. thank you very much.
